import { Inter } from 'next/font/google'
import './globals.css'
import { UserProvider } from "@/app/context/UserContext";
import { GameIdProvider } from "@/app/context/GameIdContext";
import Header from '@/app/header/header';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* test */}
      </head>
      <body className={inter.className}>
        <UserProvider>
          <GameIdProvider>
            <Header /> {/* Include header component here */}
            {children}
          </GameIdProvider>
        </UserProvider>
      </body>
    </html>
  );
}
